name: Report a Bug
description: Create a report to help us improve
title: "[Bug]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: "Thanks for reporting a bug!"
  - type: input
    id: environment
    attributes:
      label: Environment
      description: Browser, OS, game client, etc.
  - type: textarea
    id: issue
    attributes:
      label: What happened?
      description: Describe the bug and steps to reproduce
